### ISSUE TITLE
How does Nunjucks know to put the `src` files in the {{ contents }} block?

### ISSUE THREAD

**Issue by robert-snakard** [wernerglinka/ms-layout-njk#1]
I can't figure out how Nunjucks decides where to render the source files. You create a `contents` variable in body.njk. Nowhere do we set the `contents` variable. Yet somehow index.njk gets rendered there. How does Nunjucks know?

**Comment by wernerglinka** [comment]
That is a general convention. Contents refers to the body of the markdown document.

**Comment by wernerglinka** [comment]
All other "fields/variables" that you set in the frontmatter must be declared explicitly

**Comment by robert-snakard** [comment]
Wow thanks! I can't find that documented anywhere

**Comment by wernerglinka** [comment]
Documentation in not Metalsmith’s strong point. But this is explained here: https://metalsmith.io/

In section. HOW DOES IT WORK IN MORE DETAIL?



Werner Glinka
werner@glinka.co
650 867 0778

**Comment by robert-snakard** [comment]
Oh ok metalsmith convention, I was looking in the nunjucks docs.

**Comment by wernerglinka** [comment]
Yup, this is the same for any templating engine you use with Metalsmith

Werner Glinka
werner@glinka.co
650 867 0778
